# Generated by Django 5.1.2 on 2024-10-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options_cartproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='size_name',
            field=models.CharField(default='size_name', max_length=100, verbose_name='Название размера'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size_name',
            field=models.CharField(default='size_name', max_length=100, verbose_name='Название размера'),
        ),
    ]
