# Generated by Django 5.1.2 on 2024-11-02 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cartproduct_size_name_orderproduct_size_name'),
        ('main', '0005_product_brands_product_color_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='size_name',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size_name',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.size', verbose_name='Размер'),
        ),
    ]
