# Generated by Django 5.1.2 on 2024-11-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_cartproduct_size_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
