# Generated by Django 5.1.2 on 2024-11-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_img_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/', verbose_name='Изображение'),
        ),
    ]
